### ISSUE TITLE
Library update

### ISSUE THREAD

**Issue by andrelopesmrx** [guillaumedsde/comicvine-client-python#1]
How often is this library recreated? should I expect it to be automatically recreated when the API is updated?

**Comment by guillaumedsde** [comment]
Hi, I am not sure to what extent it is functional, it is generated every time their is a new commit on the master branch of the accompanying [openapi specification repository](https://github.com/guillaumedsde/comicvine-api-specification). If you're willing to give a hand, you can submit a PR there and once it is merged this repository will be updated 🙂

**Comment by andrelopesmrx** [comment]
What you said makes sense, and probably doesn't need to be changed. 

I was just trying to figure out if the error I am getting trying to run the example provided is related to some recent change at comicvine side,  get_character is failing like this:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/src/app/comicsdb/services.py", line 23, in _test
    api_response = api_instance.get_character(id, format=format, field_list=field_list)
  File "/usr/local/src/comicvine-client/comicvine_client/api/character_api.py", line 70, in get_character
    return self.get_character_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/src/comicvine-client/comicvine_client/api/character_api.py", line 160, in get_character_with_http_info
    return self.api_client.call_api(
  File "/usr/local/src/comicvine-client/comicvine_client/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/src/comicvine-client/comicvine_client/api_client.py", line 208, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/src/comicvine-client/comicvine_client/api_client.py", line 280, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/src/comicvine-client/comicvine_client/api_client.py", line 319, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/src/comicvine-client/comicvine_client/api_client.py", line 658, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/src/comicvine-client/comicvine_client/api_client.py", line 308, in __deserialize
    klass = getattr(comicvine_client.models, klass)
AttributeError: module 'comicvine_client.models' has no attribute 'OneOfVolumeIssuePersonCharacter'
>>> 
```
